INSERT INTO USER (ID, EMAIL, FIRST_NAME, LAST_NAME) VALUES(1, 'a@gmail.com','Juan', 'Perez');
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(1, 200.2, 1);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(2, 250.2, 1);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(3, 500.50, 1);

INSERT INTO USER (ID, EMAIL, FIRST_NAME, LAST_NAME) VALUES(2, 'b@gmail.com','Pepe', 'Argento');
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(4, 50.45, 2);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(5, 300, 2);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(6, 1000, 2);

INSERT INTO USER (ID, EMAIL, FIRST_NAME, LAST_NAME) VALUES(3, 'c@gmail.com','Moni', 'Argento');
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(7, 223.2, 3);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(8, 245.2, 3);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(9, 534.50, 3);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(10, 800.45, 3);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(11, 345, 3);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(12, 10450, 3);

INSERT INTO USER (ID, EMAIL, FIRST_NAME, LAST_NAME) VALUES(4, 'd@gmail.com','Koki', 'Argento');
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(13, 234.2, 4);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(14, 123.2, 4);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(15, 700.50, 4);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(16, 5000.45, 4);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(17, 342, 4);
INSERT INTO LOAN (ID, TOTAL, USER_ID) VALUES(18, 10450, 4);